// LOCAL
### GET ALL
GET http://localhost:8080/contacts

### GET ONE
GET http://localhost:8080/contacts/626c7bd21d11f4ab7ab260f5

### GET ONE (2)
GET http://localhost:8080/contacts/626c7be11d11f4ab7ab260f6

### GET ONE (3)
GET http://localhost:8080/contacts/626c7be51d11f4ab7ab260f7

### CREATE ONE
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "birthday": "May 6, 1994",
  "email": "mos15010@byui.edu",
  "favoriteColor": "Blue",
  "firstName": "Chase",
  "lastName": "Moses"
}

### UPDATE ONE
POST http://localhost:8080/contacts/626c7be51d11f4ab7ab260f7
Content-Type: application/json

{
  "birthday": "March 12, 2019",
  "email": "oliverisastud@gmail.com",
  "favoriteColor": "Green",
  "firstName": "Oliver",
  "lastName": "Moses"
}

### UPDATE PARTIAL 
POST http://localhost:8080/contacts/626c7be51d11f4ab7ab260f7
Content-Type: application/json

{
  "firstName": "Zachary",
  "lastName": "Reeves"
}

### DELETE ONE
DELETE http://localhost:8080/contacts/62774c2a0d7815c7a8ee6c40











// PRODUCTION

### GET ALL CONTACTS
GET https://cse341-lesson2.herokuapp.com/contacts

### GET ONE
GET https://cse341-lesson2.herokuapp.com/contacts/626c7bd21d11f4ab7ab260f5

### GET ONE (2)
GET https://cse341-lesson2.herokuapp.com/contacts/626c7be11d11f4ab7ab260f6

### GET ONE (3)
GET https://cse341-lesson2.herokuapp.com/contacts/626c7be51d11f4ab7ab260f7


### CREATE ONE STRETCH
POST https://cse341-lesson2.herokuapp.com/contacts
Content-Type: application/json

{
  "birthday": "May 6, 1994",
  "email": "mos15010@byui.edu",
  "favoriteColor": "Blue",
  "firstName": "Chase",
  "lastName": "Moses"
}

### UPDATE ONE STRETCH
POST https://cse341-lesson2.herokuapp.com/contacts/626c7be51d11f4ab7ab260f7
Content-Type: application/json

{
  "birthday": "July 10, 1995",
  "email": "bowmanllane@gmail.com",
  "favoriteColor": "Green",
  "firstName": "Morgan",
  "lastName": "Bowman"
}

### UPDATE PARTIAL CONTACT
POST https://cse341-lesson2.herokuapp.com/contacts/626c7be51d11f4ab7ab260f7
Content-Type: application/json

{
  "firstName": "Zachary",
  "lastName": "Reeves"
}

### DELETE ONE STRETCH **Make sure to add ID to delete
DELETE https://cse341-lesson2.herokuapp.com/contacts/626da6aaf96bac2f66c43d20